import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  scoreTimeText: {
    color: 'white',
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    justifyContent: 'center',
    display: 'flex',
  },
  scoreTimeTextIOS: {
    color: 'white',
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    justifyContent: 'center',
    display: 'flex',
  },
  scoreTimeTextAndroid: {
    color: 'white',
    fontSize: 25,
    fontWeight: 'bold',
    textAlign: 'center',
    justifyContent: 'center',
    display: 'flex',
  },
  navText: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 30,
    backgroundColor: 'orange',
    width: 'auto',
    marginHorizontal: 'auto',
    marginTop: 10,
    padding: 5,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  navTextIOS: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 30,
    backgroundColor: 'orange',
    width: 300,
    marginLeft: 365,
    padding: 5,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    marginBottom: 30,
  },
  navTextAndroid: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 30,
    backgroundColor: 'orange',
    width: 300,
    marginLeft: 355,
    padding: 5,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
    marginBottom: 30,
  },
  holes: {
    marginTop: 60,
    justifyContent: 'center',
    alignItems: 'center',
  },
  holesIOS: {
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  holesAndroid: {
    marginTop: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  holeImg: {
    width: 150,
    height: 70,
    marginHorizontal: 50,
    marginTop: 230,
  },
  holeImgIOS: {
    width: 145,
    height: 80,
    marginHorizontal: 10,
    marginTop: 95,
  },
  holeImgAndroid: {
    width: 100,
    height: 60,
    margin: 10,
    marginHorizontal: 20,
    marginTop: 91,
  },
  moleImg: {
    width: 155,
    height: 155,
    marginHorizontal: 48,
    marginTop: 145,
  },
  moleImgIOS: {
    width: 150,
    height: 150,
    marginHorizontal: 9,
    marginTop: 17,
  },
  moleImgAndroid: {
    width: 100,
    height: 115,
    margin: 10,
    marginHorizontal: 20,
    marginTop: 33,
  },
  timerText: {
    fontSize: 25,
    fontWeight: 'bold',
    color: '#FFF',
    textAlign: 'center',
  },
  timerTextAndroid: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFF',
    textAlign: 'center',
  },
  scoreLeaderboardText: {
    color: 'white',
    fontSize: 40,
    fontWeight: 'bold',
    textAlign: 'center',
    justifyContent: 'center',
    display: 'flex',
  },
  scoreLeaderboardTextIOS: {
    color: 'white',
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    justifyContent: 'center',
    display: 'flex',
    marginVertical: 40,
  },
  scoreLeaderboardTextAndroid: {
    color: 'white',
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    justifyContent: 'center',
    display: 'flex',
    marginBottom: 40,
  },
  scoreLeaderboardTextOneAndroid: {
    color: 'white',
    fontSize: 30,
    fontWeight: 'bold',
    textAlign: 'center',
    justifyContent: 'center',
    display: 'flex',
    marginTop: 40,
    marginBottom: 20,
  },
  levelTwoText: {
    color: 'white',
    fontSize: 25,
    textAlign: 'center',
    width: '50%',
    marginVertical: 80,
    marginHorizontal: 'auto',
  },
  levelTwoTextIOS: {
    color: 'white',
    fontSize: 20,
    textAlign: 'center',
    width: '25%',
    marginLeft: 385,
    marginTop: 40,
  },
  levelTwoTextAndroid: {
    color: 'white',
    fontSize: 20,
    textAlign: 'center',
    width: '30%',
    marginLeft: 350,
    marginTop: 40,
  },
  inputBox: {
    backgroundColor: 'white',
    borderStyle: 'solid',
    borderColor: 'green',
    borderRadius: 6,
    marginTop: 50,
  },
  inputBoxIOS: {
    backgroundColor: 'white',
    borderStyle: 'solid',
    borderColor: 'green',
    borderWidth: 2,
  },
  inputBoxAndroid: {
    backgroundColor: 'white',
    borderStyle: 'solid',
    borderColor: 'green',
    borderWidth: 2,
    borderRadius: 6,
  },
  submitNameText: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 30,
    backgroundColor: 'orange',
    width: 'auto',
    marginHorizontal: 'auto',
    marginTop: 10,
    padding: 5,
    borderRadius: 5,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  submitNameTextIOS: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 25,
    backgroundColor: 'orange',
    width: 'auto',
    marginHorizontal: 'auto',
    marginTop: 10,
    padding: 5,
    borderRadius: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  submitNameTextAndroid: {
    color: 'white',
    textAlign: 'center',
    fontWeight: 'bold',
    fontSize: 25,
    backgroundColor: 'orange',
    width: 'auto',
    marginHorizontal: 'auto',
    marginTop: 10,
    padding: 5,
    borderRadius: 6,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 2,
  },
  leaderboardTitle: {
    color: 'white',
    fontSize: 40,
    fontWeight: 'bold',
    marginTop: 50,
    marginBottom: 20,
    marginLeft: 10,
  },
  leaderboardTitleIOS: {
    color: 'white',
    fontSize: 30,
    fontWeight: 'bold',
    marginTop: 30,
    marginBottom: 10,
    marginLeft: 18,
  },
  leaderboardTitleAndroid: {
    color: 'white',
    fontSize: 30,
    fontWeight: 'bold',
    marginTop: 30,
    marginBottom: 10,
    marginLeft: 18,
  },
  leaderboardList: {
    color: 'white',
    fontSize: 30,
    marginLeft: 70,
  },
  leaderboardListIOS: {
    color: 'white',
    fontSize: 25,
    marginLeft: 55,
  },
  leaderboardListAndroid: {
    color: 'white',
    fontSize: 25,
    marginLeft: 55,
  },
});

// Test
var textinputstyle = (x) => ({
  fontSize: 20,
  height: 20,
  // Uncomment this and textinput 2 & 3 won't work
  top: x * 50,
  borderWidth: 1,
  borderColor: 'green',
});
